module.exports = {
  FIELD_WIDTH: 500,
  FIELD_HEIGHT: 500,

  ACCELERATION: 0.2,
  FRICTION: 0.98,
  PLAYER_RADIUS: 10,
  NPC_RADIUS: 30, // Für Sternen-Kollision in passender Größe

  BOOST_STRENGTH: 1.5,
  BOOST_COOLDOWN: 5000,

  FPS: 60,
  MAX_LEVEL: 100,

  SCORE_PER_SECOND: 50
};
